name: Build and Deploy Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
          cache-dependency-path: |
            backend/pom.xml
            config-server/pom.xml
      - name: Build backend
        run: mvn -B package -DskipTests --file backend/pom.xml

      - name: Build config-server
        run: mvn -B package -DskipTests --file config-server/pom.xml

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push friday backend
        uses: docker/build-push-action@v4
        with:
          context: backend
          push: true
          tags: ghcr.io/${{ github.repository }}/friday-backend:latest

      - name: Build and push friday config
        uses: docker/build-push-action@v4
        with:
          context: config-server
          push: true
          tags: ghcr.io/${{ github.repository }}/friday-config:latest

      - name: Log out from GitHub Container Registry
        run: docker logout ghcr.io
